import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../../context/AuthContext';
import OwnerLayout from '../../components/dashboard/OwnerLayout';
import { generateHybridReport } from '../../utils/reportGenerator';
import toast from 'react-hot-toast';

const OwnerReports = () => {
    const { user } = useAuth();
    
    // --- State ---
    const [selectedType, setSelectedType] = useState('sales');
    const [selectedRange, setSelectedRange] = useState('Weekly');
    const [loading, setLoading] = useState(true);
    const [exporting, setExporting] = useState(false);
    const [realData, setRealData] = useState(null);
    
    // Simple Report Types
    const reportTypes = [
        { id: 'sales', title: 'Sales Report', desc: 'See how much you’ve earned.', icon: 'payments' },
        { id: 'orders', title: 'Orders Report', desc: 'Summary of your latest orders.', icon: 'shopping_bag' },
        { id: 'inventory', title: 'Inventory Report', desc: 'Track your product stock levels.', icon: 'inventory_2' },
        { id: 'financial', title: 'Financial Report', desc: 'Basic profit and loss summary.', icon: 'account_balance_wallet' },
    ];

    // Simple Time Ranges
    const ranges = ['Daily', 'Weekly', 'Monthly', 'Annual'];

    // Fetch real analytics data
    useEffect(() => {
        const fetchAnalytics = async () => {
            try {
                setLoading(true);
                const token = localStorage.getItem('token');
                if (!token) return;
                
                const period = selectedRange.toLowerCase();
                const res = await axios.get(`http://localhost:5000/api/analytics/owner/kpis?period=${period}`, {
                    headers: { Authorization: `Bearer ${token}` }
                });
                
                setRealData(res.data);
            } catch (err) {
                console.error('Failed to fetch analytics', err);
                toast.error('Could not load latest business data.');
            } finally {
                setLoading(false);
            }
        };

        fetchAnalytics();
    }, [selectedRange]);

    // Map real data to preview cards
    const getPreviewData = () => {
        if (!realData) return { label1: '-', value1: '-', label2: '-', value2: '-', label3: '-', value3: '-' };

        if (selectedType === 'inventory') {
            return {
                label1: 'Low Stock Items', value1: realData.lowStock?.value || 0,
                label2: 'Tracked Items', value2: realData.topItems?.length || 0,
                label3: 'Stock Status', value3: realData.lowStock?.value > 0 ? 'Action Needed' : 'Healthy'
            };
        }
        
        const bestItem = realData.topItems?.[0]?.name || 'No Sales Yet';
        
        return {
            label1: 'Total Revenue', value1: `$${(realData.totalRevenue?.value || 0).toLocaleString()}`,
            label2: 'Orders (Period)', value2: realData.pendingOrders?.value ?? 0,
            label3: 'Best Selling Item', value3: bestItem
        };
    };

    const previewData = getPreviewData();

    // Actual report generation
    const handleDownload = async (format) => {
        if (!realData) return;
        setExporting(true);
        
        const activeReport = reportTypes.find(r => r.id === selectedType);
        const timestamp = new Date().toLocaleDateString();

        try {
            const headers = ['Metric', 'Current Period Data'];
            const reportRows = [
                ['Report Type', activeReport.title],
                ['Time Range', selectedRange],
                ['Generation Date', timestamp],
                ['Total Revenue', `$${(realData.totalRevenue?.value || 0).toLocaleString()}`],
                ['Orders Count', realData.pendingOrders?.value || 0],
                ['Low Stock Alerts', realData.lowStock?.value || 0],
                ['Top Performer', realData.topItems?.[0]?.name || 'N/A']
            ];

            if (format === 'pdf') {
                await generateHybridReport({
                    title: `Business Performance Report: ${activeReport.title}`,
                    subtitle: `Store: ${user?.storeName || 'My Store'} | Range: ${selectedRange} | Campus: HustleHub`,
                    headers,
                    data: reportRows,
                    summary: [
                        { label: 'Official Status', value: 'Verified Record' },
                        { label: 'Generated By', value: user?.firstName || 'Store Owner' }
                    ]
                }, `HustleHub_${selectedType}_${selectedRange.toLowerCase()}.pdf`);
            } else {
                // CSV Logic
                let csvContent = `data:text/csv;charset=utf-8,HustleHub Business Report,${activeReport.title}\nRange,${selectedRange}\nDate,${timestamp}\n\nMetric,Value\n`;
                reportRows.forEach(row => { csvContent += `"${row[0]}","${row[1]}"\n`; });
                const encodedUri = encodeURI(csvContent);
                const link = document.createElement("a");
                link.setAttribute("href", encodedUri);
                link.setAttribute("download", `HustleHub_${selectedType}_${selectedRange.toLowerCase()}.csv`);
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
                toast.success('Spreadsheet exported successfully');
            }
        } catch (error) {
            console.error(error);
            toast.error('Failed to generate report.');
        } finally {
            setExporting(false);
        }
    };

    return (
        <OwnerLayout activeTab="reports" headerTitle="Business Analytics">
            <div className="max-w-5xl mx-auto py-8 px-4">
                
                {/* --- Page Header --- */}
                <div className="mb-10 text-left">
                    <h1 className="text-3xl font-bold text-slate-900 mb-2">Business Reports</h1>
                    <p className="text-slate-500 text-lg">View a summary of your business performance and download reports easily.</p>
                </div>

                <div className="space-y-12">
                    
                    {/* --- 1. Choose Report Type --- */}
                    <section>
                        <h2 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-6">1. Choose a Report Type</h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                            {reportTypes.map(type => (
                                <button
                                    key={type.id}
                                    onClick={() => setSelectedType(type.id)}
                                    className={`text-left p-6 rounded-2xl border-2 transition-all group ${
                                        selectedType === type.id 
                                        ? 'bg-indigo-50 border-indigo-600 shadow-sm' 
                                        : 'bg-white border-slate-100 hover:border-slate-200'
                                    }`}
                                >
                                    <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 transition-colors ${
                                        selectedType === type.id ? 'bg-indigo-600 text-white' : 'bg-slate-50 text-slate-400 group-hover:bg-slate-100'
                                    }`}>
                                        <span className="material-symbols-outlined">{type.icon}</span>
                                    </div>
                                    <h3 className={`font-bold text-lg mb-1 ${selectedType === type.id ? 'text-indigo-900' : 'text-slate-900'}`}>
                                        {type.title}
                                    </h3>
                                    <p className="text-sm text-slate-400 leading-snug">
                                        {type.desc}
                                    </p>
                                </button>
                            ))}
                        </div>
                    </section>

                    {/* --- 2. Choose Time Range --- */}
                    <section>
                        <h2 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-6">2. Pick a Time Range</h2>
                        <div className="flex flex-wrap gap-2">
                            {ranges.map(range => (
                                <button
                                    key={range}
                                    onClick={() => setSelectedRange(range)}
                                    className={`px-6 py-3 rounded-full text-sm font-bold transition-all ${
                                        selectedRange === range 
                                        ? 'bg-slate-900 text-white shadow-lg' 
                                        : 'bg-white border border-slate-200 text-slate-500 hover:bg-slate-50'
                                    }`}
                                >
                                    {range}
                                </button>
                            ))}
                        </div>
                    </section>

                    {/* --- 3. Preview --- */}
                    <section className="bg-slate-50/50 rounded-3xl p-8 border border-dashed border-slate-200">
                        <div className="flex items-center justify-between mb-8">
                            <h2 className="text-sm font-bold text-slate-400 uppercase tracking-wider">Summary Preview</h2>
                            {!loading && realData && (
                                <p className="text-[10px] font-bold text-emerald-600 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-100 uppercase tracking-widest">
                                    Live Data Synced
                                </p>
                            )}
                        </div>
                        
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                            {[1, 2, 3].map(i => {
                                const labelKey = `label${i}`;
                                const valueKey = `value${i}`;
                                return (
                                    <div key={i} className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 h-32 flex flex-col justify-center">
                                        {loading ? (
                                            <div className="animate-pulse space-y-4">
                                                <div className="h-2 bg-slate-100 w-1/2 rounded"></div>
                                                <div className="h-6 bg-slate-100 w-full rounded"></div>
                                            </div>
                                        ) : (
                                            <>
                                                <p className="text-xs font-bold text-slate-400 mb-2 uppercase tracking-wide">{previewData[labelKey]}</p>
                                                <p className="text-2xl font-bold text-slate-900 truncate">{previewData[valueKey]}</p>
                                            </>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    </section>

                    {/* --- 4. Actions --- */}
                    <section className="flex flex-col md:flex-row items-center justify-center gap-4 pt-4">
                        <button 
                            onClick={() => handleDownload('pdf')}
                            disabled={loading || exporting || !realData}
                            className="w-full md:w-auto px-10 py-4 bg-indigo-600 text-white rounded-xl font-bold flex items-center justify-center gap-3 hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200 disabled:opacity-50"
                        >
                            <span className={`material-symbols-outlined text-xl ${exporting ? 'animate-spin' : ''}`}>
                                {exporting ? 'sync' : 'picture_as_pdf'}
                            </span>
                            {exporting ? 'Generating...' : 'Download PDF'}
                        </button>
                        
                        <button 
                            onClick={() => handleDownload('csv')}
                            disabled={loading || exporting || !realData}
                            className="w-full md:w-auto px-10 py-4 bg-white border border-slate-200 text-slate-700 rounded-xl font-bold flex items-center justify-center gap-3 hover:bg-slate-50 transition-all disabled:opacity-50"
                        >
                            <span className={`material-symbols-outlined text-xl ${exporting ? 'animate-spin' : ''}`}>
                                {exporting ? 'sync' : 'table_chart'}
                            </span>
                            Export CSV
                        </button>
                    </section>

                </div>

                {/* --- Simple Footer --- */}
                <div className="mt-20 text-center text-slate-300">
                    <p className="text-[11px] font-bold uppercase tracking-[0.2em]">HustleHub Store Analytics • Official Performance Record</p>
                </div>

            </div>
        </OwnerLayout>
    );
};

export default OwnerReports;
